LiteratureLounge/Controllers/BookController.cs
using LiteratureLounge.Controller_Extensions;
using LiteratureLounge.Models;
using LiteratureLounge.Tools;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Purrs_And_Prose.Data;
using System.Diagnostics;
using System.Security.Claims;

namespace LiteratureLounge.Controllers
{
    public class BookController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;
        BookLookup booklookup = new BookLookup();
        private readonly IWebHostEnvironment hostingEnvironment;

        public BookController(ILogger<HomeController> logger, ApplicationDbContext db, IWebHostEnvironment enviornment)
        {
            _db = db;
            _logger = logger;
            hostingEnvironment = enviornment;
        }


        public async Task<IActionResult> Index()
        {
            var userId = "DEVUSER";
           
            var userPrefs = _db.UserPreferences
                .Where(up => up.UserId == userId)
                .Include(up => up.UserPreferencesBookIndexColumns)
                .ThenInclude(upic => upic.IndexColumn)
                .FirstOrDefault();

            if (userPrefs is null)
            {
                await BookControllerExtensions.SetupDefaultUserPrefs(_db, userId);
                userPrefs = _db.UserPreferences
                    .Where(up => up.UserId == userId)
                    .Include(up => up.UserPreferencesBookIndexColumns)
                    .ThenInclude(upic => upic.IndexColumn)
                    .FirstOrDefault();
            }
                
            IEnumerable<Book> books = _db.Books.Where(b => b.Owner == userId).ToList().OrderBy(b => b.Title);
            var allColumns = _db.IndexColumns.OrderBy(ic => ic.Name).ToList();
            Dictionary<string,bool> colNames = new Dictionary<string, bool>();
            foreach (var col in allColumns) {
                colNames[col.Name] = false;
                foreach (var prefCol in userPrefs.UserPreferencesBookIndexColumns)
                {
                    if (col.Name == prefCol.IndexColumn.Name)
                    {
                        colNames[col.Name] = true;
                        continue;
                    }
                }
            }
            return View(new BookIndexViewModel { 
                Books = books, 
                UserPreferencesBookIndexColumns = userPrefs.UserPreferencesBookIndexColumns, 
                Columns = allColumns,
                UserPrefColumns = colNames});
        }

        [HttpPost]
        public async Task<IActionResult> EditIndexColumnPrefs(BookIndexViewModel model) 
        {
            var userId = "DEVUSER";
            var userPrefs = _db.UserPreferences
                .Where(up => up.UserId == userId)
                .Include(up => up.UserPreferencesBookIndexColumns)
                .ThenInclude(upic => upic.IndexColumn)
                .FirstOrDefault();
            List<UserPreferencesBookIndexColumn> userPrefIndexCols = new List<UserPreferencesBookIndexColumn>();
            var columns = _db.IndexColumns.ToList();

            foreach (var item in model.UserPrefColumns)
            {
                if (item.Value == true)
                {
                    userPrefIndexCols.Add(new UserPreferencesBookIndexColumn
                    {
                        IndexColumn = _db.IndexColumns.Where(c => c.Name == item.Key).FirstOrDefault()
                    });
                }
            }
            userPrefs.UserPreferencesBookIndexColumns = userPrefIndexCols;
            _db.Update(userPrefs);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public IActionResult Create()
        {
            var userId = "DEVUSER";
            var genres = _db.Genres.Where(g => g.Owner == userId).ToList();
            MultiSelectList _genreList = new MultiSelectList(genres, nameof(Genre.Id), nameof(Genre.Name));
            return View(new BookEditViewModel {GenreSelectItems=_genreList});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookEditViewModel model)
        {
            var userId = "DEVUSER";

            model.book.Owner = userId;
            model.book.CatalogDate = DateTime.Today.ToString();

            if (ModelState.IsValid)
            {
                if (model.book.Rating > 5)
                    model.book.Rating = 5;
                if (model.book.Rating < 0)
                    model.book.Rating = 0;

                var ISBNs = _db.Books.Where(b => b.Owner == userId).Select(b => b.ISBN).ToList();
                foreach (var _isbn in ISBNs)
                {
                    if (_isbn == model.book.ISBN)
                    {
                        TempData["Error"] = $"Book has duplicate ISBN!";
                        return RedirectToAction("Create");
                    }
                }

                foreach (var genreId in model.genreIds)
                {
                    var _genre = _db.Genres.Where(g => g.Owner == userId).Where(g => g.Id == genreId).FirstOrDefault();
                    var bg = new BookGenre { Genre = _genre };
                    model.book.BookGenres.Add(bg);
                }

                _db.Books.Add(model.book);
                await _db.SaveChangesAsync();
                TempData["Success"] = $"Added book successfully!";
                return RedirectToAction("DetailedView", new { model.book.Id });
            }
            else {
                TempData["Error"] = $"Failed to add Book! ";
                return RedirectToAction("Create");
            }
        }

        public IActionResult CreateFromISBN()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateFromISBN(ISBNBookCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.ISBN = CleanISBN(viewModel.ISBN);
                var result = await booklookup.LookupBookDetails(viewModel.ISBN);
                var userId = "DEVUSER";

                return result.Match(book =>
                {
                    book.Owner = userId;
                    var ISBNs = _db.Books.Where(b => b.Owner == userId).Select(c => c.ISBN).ToList();
                    foreach (var _isbn in ISBNs)
                    {
                        if (_isbn == book.ISBN)
                        {
                            TempData["Error"] = $"Book has duplicate ISBN!";
                            return RedirectToAction("CreateFromISBN");
                        }
                    }
                    _db.Books.Add(book);
                    _db.SaveChanges();
                    TempData["Success"] = $"Added book successfully!";
                    return RedirectToAction("Edit", new { Id = book.Id });

                }, exception =>
                {
                    TempData["Error"] = exception.Message;
                    return RedirectToAction("CreateFromISBN");
                });

            }
            else {
                TempData["Error"] = "Failed to create book!";
                return RedirectToAction("CreateFromISBN");
            }
        }

        private string CleanISBN(string isbn)
        {
            string newIsbn = isbn;
            newIsbn = newIsbn.Replace("-", string.Empty);
            newIsbn = newIsbn.Replace("\u200B", string.Empty);
            newIsbn = newIsbn.Replace(" ", string.Empty);
            return newIsbn;
        }

        // UPDATE
        public IActionResult Edit(int? id)
        {
            var userId = "DEVUSER";
            var _book = _db.Books
                .Where(b => b.Owner == userId)
                .Include(book => book.BookGenres)
                .ThenInclude(bg => bg.Genre)
                .FirstOrDefault(c => c.Id == id);

            if (_book == null)
            {
                TempData["Error"] = $"Edit Failed! Cannot find book to edit!";
                return RedirectToAction("Index");
            }

            // Populate dropdown for series names from existing books
            var _seriesNames = new List<string>();
            foreach (var _bs in _db.Books.Where(b => b.Owner == userId).Select(row => row.Series).ToArray()) 
            {
                if (_bs is not null) 
                {
                    if (!_seriesNames.Contains(_bs)) 
                    {
                        _seriesNames.Add(_bs);
                    }
                }
            }

            List<int> currentGenreIds = new List<int>();
            foreach (var bg in _book.BookGenres) 
            {
                currentGenreIds.Add(bg.Genre.Id);
            }

            var genres = _db.Genres.Where(g => g.Owner == userId).ToList();
            MultiSelectList _genreList = new MultiSelectList(genres, nameof(Genre.Id), nameof(Genre.Name), currentGenreIds);

            var model = new BookEditViewModel { book = _book, genreIds = currentGenreIds, GenreSelectItems = _genreList, SeriesNames = _seriesNames};
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.book.Rating > 5)
                    model.book.Rating = 5;
                if (model.book.Rating < 0)
                    model.book.Rating = 0;

                // If old genres are not removed then they would just keep stacking on edit
                var oldGenres = _db.BookGenres.Where(bg => bg.BookId == model.book.Id).ToList();
                foreach (var genre in oldGenres)
                {

LiteratureLounge/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using LiteratureLounge.Models;
using System.Diagnostics;
using Purrs_And_Prose.Data;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace LiteratureLounge.Controllers
{
    public class GenreController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;

        public GenreController(ApplicationDbContext db, ILogger<HomeController> logger)
        {
            _db = db;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var userId = "DEVUSER";
            IEnumerable<Genre> genres = _db.Genres.Where(g => g.Owner == userId).ToList();
            return View(genres);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Genre genre)
        { 
            if (ModelState.IsValid) 
            {
                var userId = "DEVUSER";
                genre.Owner = userId;
                var _genres = _db.Genres.Where(g => g.Owner == userId).ToList();
                foreach (var _genre in _genres)
                {
                    if (_genre.Name == genre.Name) 
                    {
                        TempData["Error"] = "Failed to Create Duplicate Genre";
                        return View();
                    }
                }
                
                _db.Genres.Add(genre);
                await _db.SaveChangesAsync();
                TempData["Success"] = "Created Genre Successfully";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Failed to Create Genre!";
            return View();
        }

        public IActionResult Delete(int? id)
        {
            var userId = "DEVUSER";
            var genre = _db.Genres.Where(g => g.Id == id && g.Owner == userId).FirstOrDefault();
            if (genre is not null)
            {
                return View(genre);
            }
            TempData["Error"] = "Action Failed. Failed to Find Genre!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Genre genre)
        {
            if (ModelState.IsValid)
            {
                _db.Genres.Remove(genre);
                await _db.SaveChangesAsync();
                TempData["Success"] = $"Deleted Genre {genre.Name} Successfully";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Failed to Delete Genre!";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            var userId = "DEVUSER";
            var genre = _db.Genres.Where(g => g.Id == id && g.Owner == userId).FirstOrDefault();
            if (genre is not null)
            {
                return View(genre);
            }
            TempData["Error"] = "Failed to Edit Genre!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Genre genre)
        {
            var userId = "DEVUSER";
            if (ModelState.IsValid) 
            {
                var _genres = _db.Genres.Where(g => g.Owner == userId).ToList();
                foreach (var _genre in _genres)
                {
                    if (_genre.Name == genre.Name)
                    {
                        TempData["Error"] = "Failed to Create Genre with Duplicate Name";
                        return RedirectToAction("Index");
                    }
                }
                genre.Owner = userId;
                _db.Genres.Update(genre);
                await _db.SaveChangesAsync();
                TempData["Success"] = $"Edited Genre {genre.Name} Successfully";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Failed to Edit Genre!";
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LiteratureLounge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bugs Books</title>
    <script type="text/javascript" src="~/js/JQuery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Journal.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="/css/splide.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bugs Books</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Books</a>
                          <div class="dropdown-menu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">View Books</a>
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="CreateFromISBN" >Create Book From ISBN</a>
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="Create">Create Book Manually</a>
                          </div>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Genres</a>
                          <div class="dropdown-menu">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">View Genres</a>
                            <a class="nav-link text-dark" asp-controller="Genre" asp-action="Create" >Create Genre</a>
                          </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
                        </li>
                    </ul>
                 @if (!(User.Identity.IsAuthenticated))
                    {
                        <a type="button" class="btn btn-primary" asp-controller="Account" asp-action="Login">Login</a>
                    }
                    else
                    {
                        <a type="button" class="btn btn-primary" asp-controller="Account" asp-action="Profile">My Profile </a>
                        <a type="button" class="btn btn-primary" asp-controller="Account" asp-action="Logout">Logout</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            <partial name="_ValidationScriptsPartial" />
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bugs Books - v0.2
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LiteratureLounge/Views/Shared/_Notification.cshtml
<script type="text/javascript" src="~/js/JQuery.js"></script>

@if (TempData["Error"] != null)
{
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}

@if (TempData["Success"] != null)
{
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}